### ISSUE TITLE
Would you mind if I submitted a pull request on your scanners package?

### ISSUE THREAD

**Issue by rwboyer** [racingmars/virtual1403#6]
# FANTASTIC WORK

had to get that out of the way, I am a huge fan and one of the first one's out of the gate grabbing the 1403 font when I stumbled across it. In any case I appreciate and admire those that put so much work into labors of love such as this package (Hercules, resurrecting VM/370, fixing bugs that are almost as old as I am, getting COBOL to work on DOS/VS, etc) I wish I had the energy and time to work on some of this stuff... 

My infinitesimal contribution is a prototype site that I'd like to put up for public use to share the wonders of green bar printouts with those where setting up, running, and using Hercules is beyond their desires. 

In any case.... I'll reuse your magnificent work (compared to my old scripted PDF green bar implementation for personal Hercules fiddling) and I'd like to keep your package in tact while providing a minor usability enhancement for my purposes and anyone else that would like to use the vprinter/scanner package without a major refactor.

My prototype (still testing) makes one tiny change to the scanner package that so far works well in the original context as well as my use (stand-alone bytes.Buffer vs net.Conn). If you don't mind I'll fork your repo apply my changes and you can take a look, otherwise I'll use the forked version but I think it would be a shame to fragment the code.

Thanks for your work and consideration.

RB

**Comment by racingmars** [comment]
I will certainly take a look. At the moment, the scanner is dependent on it being a net.Conn because we need to be able to control the read timeouts. Since VM/370 doesn't print any indication that the job is done, we depend on the read timeout to identify end-of-job (also for any OS the current MVS end-of-job regex doesn't catch).

We need to maintain the capability, but it might be good to move it elsewhere anyway... I'd like to be able to point the agent at files (e.g. printer output from simh for VAX systems or zPDT for z/OS) in addition to the Hercules sockdev printer. (Which is perhaps what you're trying to do as well?)

**Comment by rwboyer** [comment]
Great...

[Here's a working copy](https://1403.cdox.cc)

This uses scanner and vprinter imported directly from this repo. I tried two approaches. First = disambiguate EOF from other errors in the scanner and just connect to it via a socket that way you can send and EOF causes end job instead of just aborting, this works fine. with a minor change and then works the same for Hercules (again dumping whatever the scanner had up to the EOF) and other uses where you open a scanner send through a socket, close.

The other approach I took was to mock a net.Conn interface on top of a bytes.Buffer and play with the error semantics at the end when the reader was done so that the code can be used as is. That is what is working at the link above.

Again thanks for your fantastic work on the PDF render of the green-bar!

**Comment by racingmars** [comment]
Very nice site Robert! In your case I'm guessing there's no need to implement the net.Conn read timeout semantics that I depend on, because reads from the byte slice should always be instant until you hit EOF. But like I said, I want to add reading from files as well (which don't have read deadline functionality like net.Conn does), so abstracting away to a plain bytes.Buffer (or other plain []byte source) is something that I'll need to tackle.

In the end, to maintain the end-of-job timeout functionality against both network connections and open files that we're tailing (but never hit EOF on), I'm guessing the Right Way™ or Go idiomatic way will be to feed the source data (whether file, socket, or in your case uploaded bytes) into a byte (or, more probably, a []byte) channel into the scanner. The scanner can then select on reading from the channel or a time.Timer to enforce the end-of-job timeout. That way the scanner can implement the timeout itself and not depend on the capabilities of the underlying data source.

Put more succinctly: I think what I'll have to do is make the scanner read from a byte channel, then we can feed that byte channel from whatever source of bytes we want.

**Comment by rwboyer** [comment]
That’s what I did, I just implemented a net.Conn interface over a byte array in a package called byteconn and implemented the error/eof semantics that scanner expects and then fed that to scanner instead of a real net.Conn.

**Comment by rwboyer** [comment]
```
package byteconn

import (
	"bytes"
	"errors"
	"io"
	"net"
	"os"
	"time"
)

type ByteConn struct {
	b        *bytes.Buffer
	nullConn net.Conn
	done     bool
}

func NewByteConn(buf []byte) *ByteConn {
	bc := ByteConn{
		b: bytes.NewBuffer(buf),
	}
	bc.nullConn, _ = net.Dial("tcp", "127.0.0.1:0")
	bc.done = false

	return &bc
}

func (bc *ByteConn) Read(buf []byte) (int, error) {
	n, err := bc.b.Read(buf)
	if err != nil && errors.Is(err, io.EOF) {
		if bc.done {
			return n, io.EOF
		}
		bc.done = true
		return n, os.ErrDeadlineExceeded
	}
	return n, nil
}

func (bc *ByteConn) Write(buf []byte) (int, error) {
	return 0, os.ErrPermission
}

func (bc *ByteConn) Close() error                       { return nil }
func (bc *ByteConn) LocalAddr() net.Addr                { return bc.nullConn.LocalAddr() }
func (bc *ByteConn) RemoteAddr() net.Addr               { return bc.nullConn.RemoteAddr() }
func (bc *ByteConn) SetDeadline(t time.Time) error      { return nil }
func (bc *ByteConn) SetReadDeadline(t time.Time) error  { return nil }
func (bc *ByteConn) SetWriteDeadline(t time.Time) error { return nil }

```

**Comment by rwboyer** [comment]
Turns out I don't actually need the localhost dummy connection for the net.Addr endpoints so that can go and a empty or nil net.Addr can be returned in the scanner's case as it's not used.

**Comment by rwboyer** [comment]
Nice work on the blue bar and retro stuff...

One suggestion = when using 1403 paid for font in vprinter.NewProfile(...) instead of forcing uppercase like you do in retro treat it like you treat modern (IBMPlex) as the slanted hall 1403 typeface uses small caps for lower so... you'll get lower and upper like you do for Plex rather than forcing upper when there doesn't appear to be a need.

Would be a cool option for anyone using vprinter/scanner stand alone (as I am) or for Hercules agent using something modern like C or Go etc.

**Comment by racingmars** [comment]
> One suggestion = when using 1403 paid for font in vprinter.NewProfile(...) instead of forcing uppercase like you do in retro treat it like you treat modern (IBMPlex) as the slanted hall 1403 typeface uses small caps for lower so... you'll get lower and upper like you do for Plex rather than forcing upper when there doesn't appear to be a need.

Yeah...I chose to force to upper even with the Slanted Hall typeface because it seemed a bit more authentic to do so. And personally, I don't like the look of the small caps interspersed in the listings; it "breaks immersion" for me.

But I realize that's entirely just one person's preference, and others might like the flexibility. It could certainly be a config setting (and thus something that would be able to be passed in programmatically when using vprinter directly).

**Comment by rwboyer** [comment]
@racingmars 

It's kind of there from by perspective when using it as just a module as I can create a vprinter with all the parameters I was just suggesting it for users of Hercules and the entire package mostly because my logic = most old code on OS/VS, VM/370, DOS, etc are all caps anyway so it would really only effect newer code and languages that are case sensitive.

**Comment by rwboyer** [comment]
Ps. already go get'd the 1403 site that's using vprinter/scanner modules and again using as is to provide blue/green and retro especially now that you've embedded the free fonts inside vprinter.

[New features](https://1403.cdox.cc)

Is it just me or does anyone else like the embedded functionality but HATE the way that it's implemented in comments (like other things implemented in comments) that I ALWAYS miss when it's someone else's code and it sort is a WTF... oh there it is moment. I wish there was a specific pragma keyword or something as all my code schemes tend to reduce contrast for comments.

**Comment by racingmars** [comment]
> [New features](https://1403.cdox.cc)

Nice!

> Is it just me or does anyone else like the embedded functionality but HATE the way that it's implemented in comments (like other things implemented in comments) that I ALWAYS miss when it's someone else's code and it sort is a WTF... oh there it is moment. I wish there was a specific pragma keyword or something as all my code schemes tend to reduce contrast for comments.

Yeah... it's a bit *too* subtle when reading through the code. Even in my own code I sometimes lose track of where the embed is happening.

**Comment by racingmars** [comment]
Issue #8 is somewhat related -- I've implemented the ability to run the agent in a one-off fashion to print from a file. Since I didn't want the Hercules character set conversion or carriage control, but instead to just read UTF-8 files and not try to do job separation or anything, there's a new, simpler scanner that does the work.
